Repository u-root/cpu, pull requests merged in 2022-12, with the labels that each got.

#178 cpud(remote): log messages with verbose
  cmds/cpud/main.go
Labels: Awaiting Reviewer

#175 re-add decpu sorting code
  ds/ds.go
  ds/ds_test.go
Labels: Awaiting Author

#179 server.go: Redirect cmds' stderr to SSH stderr channel
  server/server.go
Labels: Awaiting Reviewer

#180 9p server: set iouint to 0 on open and creat
  client/cpu9p.go
Labels: Awaiting Reviewer

#186 client: Always set the env var CPU_TMPMNT
  client/client.go
Labels: bug, Awaiting Author

#182 p9cpu: Start a gRPC-based Rust implementation
  p9cpu/.gitignore
  p9cpu/.vscode/settings.json
  p9cpu/Cargo.lock
  p9cpu/Cargo.toml
  p9cpu/crates/9p/Cargo.toml
  p9cpu/crates/9p/src/lib.rs
  p9cpu/crates/libp9cpu/Cargo.toml
  p9cpu/crates/libp9cpu/src/lib.rs
  p9cpu/crates/p9cpu/Cargo.toml
  p9cpu/crates/p9cpu/src/p9cpu.rs
  p9cpu/crates/p9cpud/Cargo.toml
  p9cpu/crates/p9cpud/src/p9cpud.rs
Labels: Awaiting Author

#185 Fix makefile for lack of prereqs
  Makefile
Labels: Awaiting Author
