Repository u-root/cpu, pull requests merged in 2023-09, with the labels that each got.

#241 ds.Lookup(): remove usage of nil error when there len(responses)==0
  ds/ds.go
Labels: Awaiting Reviewer

#243 remove deprecated ioutil
  client/client.go
  client/cpio9p_test.go
  client/cpu9p.go
  client/cpu9p_unix_test.go
  client/fns.go
  cmds/cpu/cpu.go
  cmds/decpu/decpu.go
  server/server.go
  server/server_linux_test.go
  server/server_test.go
Labels: Awaiting Author

#247 Update u-root
  go.mod
  go.sum
Labels: automerge
